# Site settings
title: Test site
tag_text: Test site
description: An attempt at making a site using GitHub and Jekyll
url: "http://127.0.0.1:4000"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
