# Site settings
title: Sylvia Hook
tag_text: Sylvia Hook
description: R projects and more
url: "http://127.0.0.1:4000"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
